### ISSUE TITLE
error: Error gst_parse_launch(): no element "pipewiresrc" on Fedora 32

### ISSUE THREAD

**Issue by iruszpel** [fzwoch/obs-gnome-screencast#16]
It doesn't work on Fedora 32 with OBS 25.0.4 and outputs only black screen with error: Error gst_parse_launch(): no element "pipewiresrc"

`info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'GNOME Mutter Screen Cast' (gnome-mutter-screencast-source)
info: ------------------------------------------------
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
error: Error gst_parse_launch(): no element "pipewiresrc"
`

**Comment by fzwoch** [comment]
This is briefly mentioned in the `README.md`:

`You need to have GNOME Screen Cast application installed as well as the GStreamer pipewire elements.`

`pipewiresrc` is a GStreamer plugin. Most likely it is in an extra-to-be-installed package of your distribution.

**Comment by iruszpel** [comment]
Thanks, installing pipewire-gstreamer fixed the issue
