### ISSUE TITLE
How to install it on Fedora 31 ?

### ISSUE THREAD

**Issue by paul-onof** [fzwoch/obs-gnome-screencast#17]
Hello,

I downloaded the ZIP archive, extracted it and copied the folder in /usr/share/obs/obs-plugins/ but I don't see "Desktop Screencast (Wayland/X11)" in the sources.

It's the first time I try to install a plugin in OBS so I'm probably missing something...

Sorry if my question seems dummy.

Thanks for your help.

**Comment by fzwoch** [comment]
I don't know if `/usr/share/obs/obs-plugins` is the correct directory for your install and I can't tell you which one is the correct for you. You will have to figure that out.

This plugin will show up as `GNOME Mutter Screen Cast`. Perhaps you wanted https://gitlab.gnome.org/feaneron/obs-xdg-portal/?

Anyway - you will still need the GNOME screen cast application installed and need to have Screen Sharing enabled in the GNOME control center.
