### ISSUE TITLE
Mouse cursor doesn't draw even when "Draw mouse cursor" is selected.

### ISSUE THREAD

**Issue by TheSamsai** [fzwoch/obs-gnome-screencast#18]
After an update to GNOME 3.36.2 mouse cursor doesn't seem to be picked up by the plugin anymore. I also updated to a new OBS version, but I feel like this is more likely to be a GNOME-related issue rather than OBS-related. Apart from the missing mouse cursor the screen contents do get picked up without issue.

Relevant software versions:
- GNOME 3.36.2
- OBS 25.0.8

Can provide more details if needed.

**Comment by fzwoch** [comment]
Make sure your desktop session is still Wayland. I think the GNOME API skips drawing the mouse cursor when on X11 (due to performance reasons).

On Debian the upgrade to 3.36 broke screen casting in general. So I need to hold a little longer to check if there is something else..

**Comment by TheSamsai** [comment]
I checked XDG_SESSION_TYPE and it reports back as Wayland and the issue persists. In my case, apart from this issue, the screencasting works as expected on my Arch installation.

**Comment by fzwoch** [comment]
According to:

https://gitlab.gnome.org/GNOME/mutter/-/commit/c5d2fc856a28b3a4f26ffffa420cbd9ff92875bb

it looks like GNOME mutter in 3.36 needs pipewire 0.3 for screen share. Since debian is still on 2.7 I guess that will be the reason is currently does not work for me.

**Comment by fzwoch** [comment]
Debian now has GNOME 3.38 and Pipewire 0.3. Mouse cursor seems to be okay..
