### ISSUE TITLE
Blackscreen only on Wayland Gnome 3.36.2

### ISSUE THREAD

**Issue by jvellojin** [fzwoch/obs-gnome-screencast#19]
On Gnome Wayland 3.36.2, after installing the obs-gnome-screencast I having only a black screen. The screen sharing on Gnome settings is activated and gstreamer pipewire elements are installed, as suggested in the instructions. I am on Arch.

**Comment by fzwoch** [comment]
Did you check if the log gives a hint of where it fails?

**Comment by jvellojin** [comment]
> Did you check if the log gives a hint of where it fails?

Yes, it doesn't show anything to be worried, although the issue is present only on my desktop PC. I have not been able to reproduce it in my laptop.

My desktop is an i7 6700k with 16GB ram and intel gpu HD530, while my laptop is a Thinkpad X1 carbon 6th with 16GB ram and intel gpu HD620.

Maybe is a driver issue (or a missing package that is installed in the laptop, but not in the desktop...).

**Comment by fzwoch** [comment]
In theory it should not matter what GPU is being used. The API is supposed to work with X11 as well as wayland. Even a software renderer should work I believe.

You can try to add GStreamer debbuging in case the plugin makes it that far. E.g.

```shell
GST_DEBUG=3 obs
```

You can also try higher numbers to get more information. Perhaps this reveals a hint.

**Comment by jvellojin** [comment]
> In theory it should not matter what GPU is being used. The API is supposed to work with X11 as well as wayland. Even a software renderer should work I believe.
> 
> You can try to add GStreamer debbuging in case the plugin makes it that far. E.g.
> 
> ```shell
> GST_DEBUG=3 obs
> ```
> 
> You can also try higher numbers to get more information. Perhaps this reveals a hint.

Below is the original log file from OBS.  Maybe I'm missing something...
How can I run the suggested test with `GST_DEBUG=3 obs`?

`16:41:18.424: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
16:41:18.424: CPU Speed: 2170.324MHz
16:41:18.425: Physical Cores: 4, Logical Cores: 8
16:41:18.425: Physical Memory: 15459MB Total, 13716MB Free
16:41:18.425: Kernel Version: Linux 5.7.3-arch1-1
16:41:18.425: Distribution: "Arch Linux" Unknown
16:41:18.426: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
16:41:18.428: Portable mode: false
16:41:18.508: OBS 25.0.8-1 (linux)
16:41:18.508: ---------------------------------
16:41:18.509: ---------------------------------
16:41:18.509: audio settings reset:
16:41:18.509: 	samples per sec: 44100
16:41:18.509: 	speakers:        2
16:41:18.515: ---------------------------------
16:41:18.515: Initializing OpenGL...
16:41:18.585: Loading up OpenGL on adapter Intel Mesa Intel(R) HD Graphics 530 (SKL GT2)
16:41:18.585: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.1.1, shading language 4.60
16:41:18.629: ---------------------------------
16:41:18.629: video settings reset:
16:41:18.629: 	base resolution:   1920x1080
16:41:18.629: 	output resolution: 1280x720
16:41:18.629: 	downscale filter:  Bicubic
16:41:18.629: 	fps:               30/1
16:41:18.629: 	format:            NV12
16:41:18.629: 	YUV mode:          601/Partial
16:41:18.629: NV12 texture support not available
16:41:18.632: Audio monitoring device:
16:41:18.632: 	name: Por defecto
16:41:18.632: 	id: default
16:41:18.632: ---------------------------------
16:41:18.638: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
16:41:18.732: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:41:18.732: No blackmagic support
16:41:18.769: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
16:41:18.769: 
16:41:18.769: FFMPEG VAAPI supported
16:41:18.799: VLC found, VLC video source enabled
16:41:18.799: ---------------------------------
16:41:18.799:   Loaded Modules:
16:41:18.799:     vlc-video.so
16:41:18.799:     text-freetype2.so
16:41:18.799:     rtmp-services.so
16:41:18.799:     obs-x264.so
16:41:18.799:     obs-transitions.so
16:41:18.799:     obs-outputs.so
16:41:18.799:     obs-libfdk.so
16:41:18.799:     obs-filters.so
16:41:18.799:     obs-ffmpeg.so
16:41:18.799:     linux-v4l2.so
16:41:18.799:     linux-pulseaudio.so
16:41:18.799:     linux-jack.so
16:41:18.799:     linux-decklink.so
16:41:18.799:     linux-capture.so
16:41:18.799:     linux-alsa.so
16:41:18.799:     image-source.so
16:41:18.799:     gnome-mutter-screencast.so
16:41:18.799:     frontend-tools.so
16:41:18.799:     decklink-ouput-ui.so
16:41:18.799: ---------------------------------
16:41:18.799: ==== Startup complete ===============================================
16:41:18.800: Service '' not found
16:41:18.801: No scene file found, creating default scene
16:41:18.801: All scene data cleared
16:41:18.801: ------------------------------------------------
16:41:18.805: pulse-input: Server name: 'pulseaudio 13.0'
16:41:18.805: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
16:41:18.805: pulse-input: Started recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
16:41:18.807: pulse-input: Server name: 'pulseaudio 13.0'
16:41:18.807: pulse-input: Audio format: s16le, 44100 Hz, 1 channels
16:41:18.807: pulse-input: Started recording from 'alsa_input.usb-Microsoft_Microsoft___LifeCam_HD-3000-02.mono-fallback'
16:41:18.807: Switched to scene 'Escena'
16:41:18.807: Failed to glob scene collections
16:41:19.469: [rtmp-services plugin] Successfully updated file 'services.json' (version 133)
16:41:19.469: [rtmp-services plugin] Successfully updated package (version 133)
16:41:19.595: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
16:41:19.595: 
16:41:29.315: 
16:41:29.315: ==== Auto-config wizard testing commencing ======

16:41:29.365: ---------------------------------
16:41:29.365: video settings reset:
16:41:29.365: 	base resolution:   1920x1080
16:41:29.365: 	output resolution: 1920x1080
16:41:29.365: 	downscale filter:  Bicubic
16:41:29.365: 	fps:               30/1
16:41:29.365: 	format:            NV12
16:41:29.365: 	YUV mode:          601/Partial
16:41:29.365: NV12 texture support not available
16:41:29.369: ---------------------------------
16:41:29.369: [x264 encoder: 'test_x264'] preset: veryfast
16:41:29.369: [x264 encoder: 'test_x264'] profile: high
16:41:29.370: [x264 encoder: 'test_x264'] settings:
16:41:29.370: 	rate_control: CRF
16:41:29.370: 	bitrate:      0
16:41:29.370: 	buffer size:  0
16:41:29.370: 	crf:          20
16:41:29.370: 	fps_num:      30
16:41:29.370: 	fps_den:      1
16:41:29.370: 	width:        1920
16:41:29.370: 	height:       1080
16:41:29.370: 	keyint:       250
16:41:29.370: 
16:41:29.379: ---------------------------------
16:41:29.380: [FFmpeg aac encoder: 'test_aac'] bitrate: 32, channels: 2, channel_layout: 3
16:41:29.380: 
16:41:34.387: Output 'null': stopping
16:41:34.388: Output 'null': Total frames output: 123
16:41:34.388: Output 'null': Total drawn frames: 150
16:41:34.536: ---------------------------------
16:41:34.536: video settings reset:
16:41:34.536: 	base resolution:   1920x1080
16:41:34.536: 	output resolution: 1280x720
16:41:34.536: 	downscale filter:  Bicubic
16:41:34.536: 	fps:               30/1
16:41:34.536: 	format:            NV12
16:41:34.536: 	YUV mode:          601/Partial
16:41:34.536: NV12 texture support not available
16:41:34.537: ---------------------------------
16:41:34.537: [x264 encoder: 'test_x264'] preset: veryfast
16:41:34.537: [x264 encoder: 'test_x264'] profile: high
16:41:34.537: [x264 encoder: 'test_x264'] settings:
16:41:34.537: 	rate_control: CRF
16:41:34.537: 	bitrate:      0
16:41:34.537: 	buffer size:  0
16:41:34.537: 	crf:          20
16:41:34.537: 	fps_num:      30
16:41:34.537: 	fps_den:      1
16:41:34.537: 	width:        1280
16:41:34.537: 	height:       720
16:41:34.537: 	keyint:       250
16:41:34.537: 
16:41:34.540: ---------------------------------
16:41:34.540: [FFmpeg aac encoder: 'test_aac'] bitrate: 32, channels: 2, channel_layout: 3
16:41:34.540: 
16:41:39.541: Output 'null': stopping
16:41:39.541: Output 'null': Total frames output: 122
16:41:39.541: Output 'null': Total drawn frames: 150
16:41:39.637: ---------------------------------
16:41:39.637: video settings reset:
16:41:39.637: 	base resolution:   1920x1080
16:41:39.637: 	output resolution: 1148x646
16:41:39.637: 	downscale filter:  Bicubic
16:41:39.637: 	fps:               30/1
16:41:39.637: 	format:            NV12
16:41:39.637: 	YUV mode:          601/Partial
16:41:39.637: NV12 texture support not available
16:41:39.639: ---------------------------------
16:41:39.639: [x264 encoder: 'test_x264'] preset: veryfast
16:41:39.639: [x264 encoder: 'test_x264'] profile: high
16:41:39.639: [x264 encoder: 'test_x264'] settings:
16:41:39.639: 	rate_control: CRF
16:41:39.639: 	bitrate:      0
16:41:39.639: 	buffer size:  0
16:41:39.639: 	crf:          20
16:41:39.639: 	fps_num:      30
16:41:39.639: 	fps_den:      1
16:41:39.639: 	width:        1148
16:41:39.639: 	height:       646
16:41:39.639: 	keyint:       250
16:41:39.639: 
16:41:39.642: ---------------------------------
16:41:39.642: [FFmpeg aac encoder: 'test_aac'] bitrate: 32, channels: 2, channel_layout: 3
16:41:39.642: 
16:41:44.642: Output 'null': stopping
16:41:44.642: Output 'null': Total frames output: 122
16:41:44.642: Output 'null': Total drawn frames: 150
16:41:44.740: ---------------------------------
16:41:44.740: video settings reset:
16:41:44.740: 	base resolution:   1920x1080
16:41:44.740: 	output resolution: 1280x720
16:41:44.740: 	downscale filter:  Bicubic
16:41:44.740: 	fps:               30/1
16:41:44.740: 	format:            NV12
16:41:44.740: 	YUV mode:          601/Partial
16:41:44.740: NV12 texture support not available
16:42:21.010: ---------------------------------
16:42:21.010: video settings reset:
16:42:21.010: 	base resolution:   1920x1080
16:42:21.010: 	output resolution: 1920x1080
16:42:21.010: 	downscale filter:  Bicubic
16:42:21.010: 	fps:               30/1
16:42:21.010: 	format:            NV12
16:42:21.010: 	YUV mode:          601/Partial
16:42:21.010: NV12 texture support not available
16:42:21.017: 
16:42:21.017: ==== Auto-config wizard testing stopping ========

16:42:29.366: User added source 'GNOME Mutter Screen Cast' (gnome-mutter-screencast-source) to scene 'Escena'`

**Comment by fzwoch** [comment]
Run it from a terminal.

**Comment by jvellojin** [comment]
> Run it from a terminal.

I have been able to fix it. The plugin was installed using an AUR PKGBUILD. Instead of that, I extracted the file from master release to `/usr/lib/obs-plugins` and everything is working now.
Thank you for your time and thank you for the plugin. This issue can be closed now.

**Comment by fzwoch** [comment]
Glad to hear that it works :+1:
