### ISSUE TITLE
It is super stutter on Wayland.

### ISSUE THREAD

**Issue by laichiaheng** [fzwoch/obs-gnome-screencast#20]
[2020-09-29 16-06-26.zip](https://github.com/fzwoch/obs-gnome-screencast/files/5297467/2020-09-29.16-06-26.zip)
It is how it looks like.

**Comment by fzwoch** [comment]
Zero information given. Does GNOME screen cast itself is actually okay? Most likely it is an issue with upstream and not this plugin.

**Comment by laichiaheng** [comment]
> Zero information given. Does GNOME screen cast itself is actually okay? Most likely it is an issue with upstream and not this plugin.

How to know if it's the screen cast problem or the plugin's problem?

OS: Manjaro
Gnome Shell: 3.36.6
Plugin: obs-gnome-screencast 0.1.1-1

**Comment by laichiaheng** [comment]
@fzwoch It seems to work without problem on Gnome 3.38
