### ISSUE TITLE
Incorrect handling of HIDPI display with 200% scaling when capturing in single-screen mode

### ISSUE THREAD

**Issue by VladimirP1** [fzwoch/obs-gnome-screencast#4]
I see only a quarter of my screen in OBS if I select Screen0 from the screen dropdown. If I select desktop, everything is fine.
This is under wayland.

![2019-02-04 22-21-47](https://user-images.githubusercontent.com/10977352/52232463-aa2d1a00-28cd-11e9-9d31-6e7809d4f5dc.png)

**Comment by fzwoch** [comment]
Thanks for the report. The above commit may help for your issue. At least it seemed to work for my secondary 4:3 screen when I put GNOME into HiDPI (I need more pixels..). I kinda assume it will fail if you capture your non-primary monitor and you have set a (different) per-monitor HiDPI setting..
