### ISSUE TITLE
Not showing up as source

### ISSUE THREAD

**Issue by krmax44** [fzwoch/obs-gnome-screencast#5]
Hi,

I installed the plugin by copying `gnome-screencast.so` into `/usr/local/lib/obs-plugins`, but unfortunately it did not appear in OBS as a source option, even after a reboot.

What am I missing?

**Comment by fzwoch** [comment]
How did you install all the things? Did you compile OBS yourself? Did you compile the plugin yourself? What system are you on?

Make sure `/usr/local/lib/obs-plugins` is the right plugin directory for that OBS version you are running. Depending how and which OBS you have installed this may be different. But I guess there are other plugins in that folder already?

Try running `ldd /usr/local/lib/obs-plugins/gnome-screencast.so` and check if it can find locations for all the libraries listed (if there is a `not found` hint you are missing a required package).

Try running OBS from a terminal and check its output. It may give some hints whether the loading of the plugin fails - or it may not be listed in the first place - in that case it may be the wrong plugin directory.

**Comment by krmax44** [comment]
Fixed the problem by finding this repo as an AUR package that installed without any problems (overlooked it when searching for the first time). Thanks for your help, it will probably help any other Linux newbies as well.

**Comment by jameswilddev** [comment]
As a note, I found the path to be `/usr/lib/obs-plugins`.
